"""Inpainting template featurizer for Protenix.

Reads a template CIF file and inpainting_metadata.json,
then maps template atom coordinates onto the Protenix atom array.

Atom matching strategy (same as patchr featurizerv2.py):
  - 3-way match: chain_id + residue_index + atom_name
  - Matched atoms  → template_coords[i] = template_xyz,  mask[i] = 1
  - Unmatched atoms → template_coords[i] = 0,             mask[i] = 0
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np

try:
    import biotite.structure as struc
    try:
        import biotite.structure.io.pdbx as pdbx_io  # biotite >= 0.41
        _BIOTITE_PDBX = True
    except ImportError:
        import biotite.structure.io.mmcif as pdbx_io  # biotite < 0.41
        _BIOTITE_PDBX = False
    from biotite.structure import AtomArray
    _BIOTITE_AVAILABLE = True
except ImportError:
    _BIOTITE_AVAILABLE = False
    AtomArray = object  # type: ignore[assignment,misc]


def _parse_template_cif(cif_path: str) -> "AtomArray":
    """Parse a mmCIF file and return an AtomArray with all atoms."""
    if not _BIOTITE_AVAILABLE:
        raise ImportError("biotite is required for inpainting template parsing. "
                          "Install it with: pip install biotite")
    cif_file = pdbx_io.CIFFile.read(cif_path)
    atom_array = pdbx_io.get_structure(cif_file, model=1, use_author_fields=False)
    # get_structure may return AtomArrayStack for multi-model files
    if hasattr(atom_array, "__len__") and not isinstance(atom_array, AtomArray):
        atom_array = atom_array[0]
    return atom_array


def _build_template_lookup(
    template_array: "AtomArray",
) -> Dict[tuple, np.ndarray]:
    """Build a dict: (cif_chain_id, res_id, atom_name) → xyz coords.

    Args:
        template_array: Biotite AtomArray from template CIF.
    Returns:
        Dict mapping (cif_chain_id, res_id, atom_name) → np.ndarray [3].
    """
    lookup: Dict[tuple, np.ndarray] = {}
    for i in range(len(template_array)):
        atom = template_array[i]
        # CIF atoms use label_asym_id; we stored auth_asym_id in generate_inpainting_template
        # Try label_asym_id first, fall back to chain_id
        cif_chain = str(atom.chain_id)
        res_id = int(atom.res_id)
        atom_name = str(atom.atom_name)
        key = (cif_chain, res_id, atom_name)
        lookup[key] = atom.coord
    return lookup


def _load_metadata(metadata_path: str) -> Dict[str, Dict]:
    """Load inpainting_metadata.json → {author_chain_id: {fully_fixed_residues, ...}}."""
    with open(metadata_path) as f:
        raw = json.load(f)
    # Support both {"chains": {...}} (patchr format) and flat {"A": {...}} formats
    if "chains" in raw:
        return raw["chains"]
    return raw


def _build_fixed_residue_sets(
    metadata: Dict[str, Dict],
    chain_id_mapping: Dict[str, str],  # protenix_label → author_chain
) -> Dict[str, set]:
    """Build per-protenix-chain set of fixed residue indices.

    Fixed = fully_fixed_residues ∪ (partially_fixed_residues that have atoms).
    The metadata uses author chain IDs; we invert chain_id_mapping to look them up.

    Returns:
        Dict: protenix_label_asym_id → set of 1-based residue indices that are FIXED.
    """
    # Invert mapping: author_chain → list of protenix labels
    author_to_protenix: Dict[str, List[str]] = {}
    for ptx_id, auth_id in chain_id_mapping.items():
        author_to_protenix.setdefault(auth_id, []).append(ptx_id)

    fixed_per_protenix: Dict[str, set] = {}
    for auth_id, chain_meta in metadata.items():
        fixed = set(chain_meta.get("fully_fixed_residues", []))
        for pf in chain_meta.get("partially_fixed_residues", []):
            # partially_fixed_residues may be int or dict {"residue": N, ...}
            if isinstance(pf, dict):
                fixed.add(pf.get("residue", pf.get("position")))
            else:
                fixed.add(int(pf))
        for ptx_id in author_to_protenix.get(auth_id, []):
            fixed_per_protenix[ptx_id] = fixed

    return fixed_per_protenix


def compute_inpainting_template_features(
    atom_array: "AtomArray",
    template_cif_path: str,
    metadata_path: Optional[str] = None,
    chain_id_mapping: Optional[Dict[str, str]] = None,
) -> tuple[np.ndarray, np.ndarray]:
    """Compute per-atom inpainting template features for a Protenix atom array.

    Args:
        atom_array: Protenix full atom array (from json_to_feature.SampleDictToFeatures).
        template_cif_path: Path to the template CIF file generated by
            generate_inpainting_template.
        metadata_path: Path to inpainting_metadata.json generated by
            generate_inpainting_template.  If None, all atoms present in
            the template CIF are treated as fixed.
        chain_id_mapping: Maps Protenix sequential label_asym_id (e.g. "A", "B")
            → patchr author_chain_id in CIF/metadata (e.g. "AA", "AB").
            If None, assumes 1-to-1 identity mapping (A→A, B→B, ...).

    Returns:
        template_coords: np.ndarray [N_atom, 3], float32.
            Template coordinates for matched atoms, zeros otherwise.
        template_mask: np.ndarray [N_atom], int64.
            1 for template-fixed atoms, 0 for inpainted atoms.
    """
    if not _BIOTITE_AVAILABLE:
        raise ImportError("biotite is required for inpainting. pip install biotite")

    if chain_id_mapping is None:
        chain_id_mapping = {}

    # Parse template CIF
    template_array = _parse_template_cif(template_cif_path)

    # Build lookup: (cif_chain_id, res_id, atom_name) → xyz
    template_lookup = _build_template_lookup(template_array)

    # Determine fixed residues per chain
    if metadata_path is not None:
        # Load metadata and determine which residues are fixed per Protenix chain
        metadata = _load_metadata(metadata_path)
        fixed_per_chain = _build_fixed_residue_sets(metadata, chain_id_mapping)
    else:
        # No metadata: all residues present in template CIF are fixed
        fixed_per_chain = None

    n_atoms = len(atom_array)
    template_coords = np.zeros((n_atoms, 3), dtype=np.float32)
    template_mask = np.zeros(n_atoms, dtype=np.int64)

    for i in range(n_atoms):
        atom = atom_array[i]
        # biotite uses chain_id (= label_asym_id when use_author_fields=False)
        ptx_chain_id = str(atom.chain_id)
        res_id = int(atom.res_id)
        atom_name = str(atom.atom_name)

        # Map Protenix chain → CIF chain for template lookup
        cif_chain_id = chain_id_mapping.get(ptx_chain_id, ptx_chain_id)

        # Check if this residue is in the fixed set (when metadata is available)
        if fixed_per_chain is not None:
            fixed_residues = fixed_per_chain.get(ptx_chain_id, set())
            if res_id not in fixed_residues:
                # Inpainted region: leave zeros, mask=0
                continue

        # Look up template atom coordinates
        key = (cif_chain_id, res_id, atom_name)
        if key in template_lookup:
            template_coords[i] = template_lookup[key]
            template_mask[i] = 1
        # else: atom not in template (partial residue) → mask stays 0

    n_fixed = int(template_mask.sum())
    n_total = n_atoms
    print(f"[InpaintingTemplate] {n_fixed}/{n_total} atoms fixed from template "
          f"(CIF: {Path(template_cif_path).name})")
    return template_coords, template_mask
